<a href="https://colab.research.google.com/github/DivyaSadhana/Prediction-of-Hospitalization-rate-based-on-Age-Vaccine-Manufacturer-Number-of-days-for-event-Onse/blob/main/Decision_Tree_Algorithm.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# Establish connection between My Drive and Google colab

from google.colab import drive
drive.mount('/content/gdrive')

Mounted at /content/gdrive


In [2]:
# Import File

import pandas as pd
df = pd.read_excel(r'/content/gdrive/My Drive/2023_Master_Tracker.xlsx')
df

VAERS_ID   RECVDATE STATE  AGE_YRS  CAGE_YR  CAGE_MO SEX RPT_DATE  \
0        2547730 2023-01-01    DE    53.00      NaN      NaN   F      NaN   
1        2547730 2023-01-01    DE    53.00      NaN      NaN   F      NaN   
2        2547730 2023-01-01    DE    53.00      NaN      NaN   F      NaN   
3        2547731 2023-01-01    MA     6.00      6.0      NaN   M      NaN   
4        2547732 2023-01-01    MA    38.00     38.0      NaN   F      NaN   
...          ...        ...   ...      ...      ...      ...  ..      ...   
155172   2717538 2023-11-24    CO      NaN      NaN      NaN   U      NaN   
155173   2717539 2023-11-24    NY    71.00      NaN      NaN   F      NaN   
155174   2717539 2023-11-24    NY    71.00      NaN      NaN   F      NaN   
155175   2624988 2023-05-02    WA     1.58      1.0      0.7   M      NaN   
155176   2624988 2023-05-02    WA     1.58      1.0      0.7   M      NaN   

                                             SYMPTOM_TEXT DIED  ...  \
0       The adverse event is that the patient went int...  NaN  ...   
1       The adverse event is that the patient went int...  NaN  ...   
2       The adverse event is that the patient went int...  NaN  ...   
3                        Error: Incorrect Reconstitution-  NaN  ...   
4            Error: Patient Accidentally Stuck by Needle-  NaN  ...   
...                                                   ...  ...  ...   
155172  breast cancer; This spontaneous case was repor...  NaN  ...   
155173  I could barely lift my arm/ could barely move;...  NaN  ...   
155174  I could barely lift my arm/ could barely move;...  NaN  ...   
155175  Patient received monovalent vaccine on Friday,...  NaN  ...   
155176  Patient received monovalent vaccine on Friday,...  NaN  ...   

                 SYMPTOM3                    SYMPTOM4  \
0                    Coma       Computerised tomogram   
1         Laboratory test  Magnetic resonance imaging   
2                   X-ray                         NaN   
3                     NaN                         NaN   
4                     NaN                         NaN   
...                   ...                         ...   
155172                NaN                         NaN   
155173            Fatigue              Gait inability   
155174  Pain in extremity                         NaN   
155175                NaN                         NaN   
155176                NaN                         NaN   

                                 SYMPTOM5   VAX_TYPE         VAX_MANU  \
0                  Exposure to SARS-CoV-2    COVID19          JANSSEN   
1       SARS-CoV-2 antibody test negative    COVID19          JANSSEN   
2                                     NaN    COVID19          JANSSEN   
3                                     NaN    COVID19  PFIZER\BIONTECH   
4                                     NaN  COVID19-2          MODERNA   
...                                   ...        ...              ...   
155172                                NaN    COVID19          MODERNA   
155173                      Lymphadenitis    COVID19          MODERNA   
155174                                NaN    COVID19          MODERNA   
155175                                NaN    COVID19          MODERNA   
155176                                NaN       FLU4   SANOFI PASTEUR   

         VAX_LOT VAX_DOSE_SERIES VAX_ROUTE VAX_SITE  \
0        1808982             UNK       SYR       AR   
1        1808982             UNK       SYR       AR   
2        1808982             UNK       SYR       AR   
3         GK1657               3        IM       LA   
4        141H22A               4        IM       LA   
...          ...             ...       ...      ...   
155172       NaN             UNK       NaN      NaN   
155173       NaN               6       NaN      NaN   
155174       NaN               6       NaN      NaN   
155175   AS1417B               1        IM       LL   
155176  UT7723NA               2        IM       RL   

       

In [3]:
df = df.drop_duplicates(subset='VAERS_ID', keep=False)
df

VAERS_ID   RECVDATE STATE  AGE_YRS  CAGE_YR  CAGE_MO SEX RPT_DATE  \
3        2547731 2023-01-01    MA      6.0      6.0      NaN   M      NaN   
4        2547732 2023-01-01    MA     38.0     38.0      NaN   F      NaN   
5        2547733 2023-01-01    CA     63.0     63.0      NaN   M      NaN   
6        2547734 2023-01-01    IL     30.0     30.0      NaN   F      NaN   
7        2547735 2023-01-01    LA     38.0     38.0      NaN   F      NaN   
...          ...        ...   ...      ...      ...      ...  ..      ...   
155168   2717531 2023-11-24    TX     16.0      NaN      NaN   F      NaN   
155169   2717532 2023-11-24    AL     30.0     30.0      NaN   F      NaN   
155170   2717536 2023-11-24   NaN      NaN      NaN      NaN   U      NaN   
155171   2717537 2023-11-24    CA      NaN      NaN      NaN   M      NaN   
155172   2717538 2023-11-24    CO      NaN      NaN      NaN   U      NaN   

                                             SYMPTOM_TEXT DIED  ...  \
3                        Error: Incorrect Reconstitution-  NaN  ...   
4            Error: Patient Accidentally Stuck by Needle-  NaN  ...   
5                  Error: Dose in Series Given Too Early-  NaN  ...   
6                          Systemic: EYE TWITCHING-Medium  NaN  ...   
7       Systemic: Confusion-Mild, Systemic: Fainting /...  NaN  ...   
...                                                   ...  ...  ...   
155168  16 year old patient was given an extra dose of...  NaN  ...   
155169  she received Fluzone Quadrivalent and is curre...  NaN  ...   
155170  arm is in a lot of pain; Swollen arm; This non...  NaN  ...   
155171  ill; liver transplant; This serious case was r...  NaN  ...   
155172  breast cancer; This spontaneous case was repor...  NaN  ...   

          SYMPTOM3 SYMPTOM4                 SYMPTOM5   VAX_TYPE  \
3              NaN      NaN                      NaN    COVID19   
4              NaN      NaN                      NaN  COVID19-2   
5              NaN      NaN                      NaN    COVID19   
6              NaN      NaN                      NaN       TDAP   
7       Dysarthria  Syncope  Unresponsive to stimuli  COVID19-2   
...            ...      ...                      ...        ...   
155168         NaN      NaN                      NaN       TDAP   
155169         NaN      NaN                      NaN       FLU4   
155170         NaN      NaN                      NaN        RSV   
155171         NaN      NaN                      NaN     VARZOS   
155172         NaN      NaN                      NaN    COVID19   

                           VAX_MANU   VAX_LOT VAX_DOSE_SERIES VAX_ROUTE  \
3                   PFIZER\BIONTECH    GK1657               3        IM   
4                           MODERNA   141H22A               4        IM   
5                           MODERNA   042h22a               1        IM   
6       GLAXOSMITHKLINE BIOLOGICALS     KP547               1        IM   
7                   PFIZER\BIONTECH    GJ3274             NaN        IM   
...                             ...       ...             ...       ...   
155168               SANOFI PASTEUR   U7648AA             UNK        OT   
155169               SANOFI PASTEUR  UT8144NA             UNK        OT   
155170  GLAXOSMITHKLINE BIOLOGICALS       UNK             UNK       NaN   
155171  GLAXOSMITHKLINE BIOLOGICALS       NaN               1       NaN   
155172                      MODERNA       NaN             UNK       NaN   

       VAX_SITE                                      VAX_NAME  
3            LA           COVID19 (COVID19 (PFIZER-BIONTECH))  
4            LA          COVID19 (COVID19 (MODERNA BIVALENT))  
5            LA                   COVID19 (COVID19 (MODERNA))  
6            LA                               TDAP (BOOSTRIX)  
7            LA  COVID19 (COVID19 (PFIZER-BIONTECH BIVALENT))  
...         ...                                           ...  
155168      NaN                                 TDAP (ADACEL)  
155169      

# Model 1: Without Binning and Without K-Fold

In [19]:
DataFrame = df[['AGE_YRS','NUMDAYS','VAX_MANU','HOSPITAL']]
DataFrame.head(2)

AGE_YRS  NUMDAYS         VAX_MANU HOSPITAL
3      6.0      0.0  PFIZER\BIONTECH      NaN
4     38.0      0.0          MODERNA      NaN

In [20]:
from sklearn.metrics import confusion_matrix, f1_score, recall_score
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, precision_score
from sklearn.preprocessing import LabelEncoder

# Assuming DataFrame is your DataFrame
# Fill null values of all columns with 0
DataFrame = DataFrame.fillna(0)

# Ensure that all columns are of type string before performing label encoding
DataFrame = DataFrame.astype(str)

Features1 = DataFrame.drop('HOSPITAL', axis=1)  # Features (all columns except 'HOSPITAL')
Label1 = DataFrame['HOSPITAL']   # Target ('HOSPITAL' column)

# Exclude rows where 'NUMDAYS' > 31
Features1 = Features1[Features1['NUMDAYS'].astype(float) <= 31]
Label1 = Label1.loc[Features1.index]

# Split the data into training and testing sets
Features1_train, Features1_test, Label1_train, Label1_test = train_test_split(Features1, Label1, test_size=0.2, random_state=42, stratify=Label1)

# Print the number of training and test cases
print(f"Number of training cases: {len(Features1_train)}")
print(f"Number of test cases: {len(Features1_test)}")

# Transform 'HOSPITAL' rows value with "Y" to 1 and null values of 'HOSPITAL' to 0
Label1_train = Label1_train.apply(lambda x: 1 if x == 'Y' else 0)
Label1_test = Label1_test.apply(lambda x: 1 if x == 'Y' else 0)

# Transform 'VAX_MANU' performing LabelEncoder to convert categorical values of 'VAX_MANU' to integers
encoder = LabelEncoder()
Features1_train['VAX_MANU'] = encoder.fit_transform(Features1_train['VAX_MANU'])  # Already string, so no need to convert
Features1_test['VAX_MANU'] = encoder.transform(Features1_test['VAX_MANU'])  # Use transform() for test set to avoid data leakage

# Change data type of features, labels datasets of training, test dataset into integers
Features1_train = Features1_train.astype(float).astype(int)
Features1_test = Features1_test.astype(float).astype(int)
Label1_train = Label1_train.astype(int)
Label1_test = Label1_test.astype(int)

# Create a decision tree classifier and fit it to the training data
DecisionTree_Model = DecisionTreeClassifier(criterion='gini')
DecisionTree_Model.fit(Features1_train, Label1_train)

# Make predictions on the testing set
Label1_pred = DecisionTree_Model.predict(Features1_test)

# Calculate the accuracy and precision of the model
Accuracy = DecisionTree_Model.score(Features1_test, Label1_test)
Precision = precision_score(Label1_test, Label1_pred, average='weighted')  # Use 'weighted' for multi-class classification
F1 = f1_score(Label1_test, Label1_pred, average='weighted')  # Use 'weighted' for multi-class classification
Recall = recall_score(Label1_test, Label1_pred, average='weighted')  # Use 'weighted' for multi-class classification

# Calculate and print the confusion matrix
Confusion_Matrix = confusion_matrix(Label1_test, Label1_pred)

print(f"Accuracy: {Accuracy}")
print(f"Precision: {Precision}")
print(f"F1 Score: {F1}")
print(f"Recall: {Recall}")
print(f"Confusion Matrix: \n{Confusion_Matrix}")


Number of training cases: 46585
Number of test cases: 11647
Accuracy: 0.966944277496351
Precision: 0.9615281960333453
F1 Score: 0.9638937041652917
Recall: 0.966944277496351
Confusion Matrix: 
[[11177   140]
 [  245    85]]


In [21]:
import pandas as pd

# Assuming your features are named 'Feature1', 'Feature2', 'Feature3'
Features1 = ['AGE_YRS','NUMDAYS','VAX_MANU']

# Your input data
data_input = [90, 22, 9]

# Convert your input data into a DataFrame with feature names
data_input_df = pd.DataFrame([data_input], columns=Features1)

# Now you can predict with your model
prediction = DecisionTree_Model.predict(data_input_df)

print(f"Input_Class: {data_input_df}")
print(f"Prediction_Class: {prediction}")

Input_Class:    AGE_YRS  NUMDAYS  VAX_MANU
0       90       22         9
Prediction_Class: [1]


In [24]:
# Assuming your features are named 'Feature1', 'Feature2', 'Feature3'
Features1 = ['AGE_YRS','NUMDAYS','VAX_MANU']

# Your input data
data_input = [90, 22, 23]

# Convert your input data into a DataFrame with feature names
data_input_df = pd.DataFrame([data_input], columns=Features1)

# Now you can predict with your model
prediction = DecisionTree_Model.predict(data_input_df)

print(f"Input_Class: {data_input_df}")
print(f"Prediction_Class: {prediction}")

Input_Class:    AGE_YRS  NUMDAYS  VAX_MANU
0       90       22        23
Prediction_Class: [0]


In [23]:
import pandas as pd

# Assuming your features are named 'Feature1', 'Feature2', 'Feature3'
Features1 = ['AGE_YRS','NUMDAYS','VAX_MANU']

# Your input data
data_input = [90, 18, 8]

# Convert your input data into a DataFrame with feature names
data_input_df = pd.DataFrame([data_input], columns=Features1)

# Now you can predict with your model
prediction = DecisionTree_Model.predict(data_input_df)

print(f"Input_Class: {data_input_df}")
print(f"Prediction_Class: {prediction}")

Input_Class:    AGE_YRS  NUMDAYS  VAX_MANU
0       90       18         8
Prediction_Class: [0]


#Model 2 : Binning was performed with Age, Numdays columns

In [14]:
DataTable = df[['AGE_YRS','NUMDAYS','VAX_MANU','HOSPITAL']]
DataTable.head(2)

AGE_YRS  NUMDAYS         VAX_MANU HOSPITAL
3      6.0      0.0  PFIZER\BIONTECH      NaN
4     38.0      0.0          MODERNA      NaN

In [15]:
from sklearn.metrics import confusion_matrix, f1_score, recall_score
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, precision_score
from sklearn.preprocessing import LabelEncoder
import pandas as pd

# Assuming DataTable is your DataFrame
# Fill null values of all columns with 0
DataTable = DataTable.fillna(0)

# Ensure that all columns are of type string before performing label encoding
DataTable = DataTable.astype(str)

Features2 = DataTable[['AGE_YRS', 'NUMDAYS', 'VAX_MANU']]  # Features ('AGE_YRS', 'NUMDAYS', 'VAX_MANU')
Label2 = DataTable['HOSPITAL']   # Target ('HOSPITAL' column)

# Split the data into training and testing sets
Features_train, Features_test, Label_train, Label_test = train_test_split(Features2, Label2, test_size=0.2, random_state=42, stratify=Label2)
# Print the number of training and test cases
print(f"Number of training cases: {len(Features_train)}")
print(f"Number of test cases: {len(Features_test)}")

# Transform 'HOSPITAL' rows value with "Y" to 1 and null values of 'HOSPITAL' to 0
Label_train = Label_train.apply(lambda x: 1 if x == 'Y' else 0)
Label_test = Label_test.apply(lambda x: 1 if x == 'Y' else 0)

# Exclude rows where 'NUMDAYS' > 31 in training and testing sets
Features_train = Features_train[Features_train['NUMDAYS'].astype(float) <= 31]
Label_train = Label_train.loc[Features_train.index]
Features_test = Features_test[Features_test['NUMDAYS'].astype(float) <= 31]
Label_test = Label_test.loc[Features_test.index]

# Exclude null values of 'AGE' and 'NUMDAYS' in training and testing sets
Features_train = Features_train[Features_train['AGE_YRS'].notnull() & Features_train['NUMDAYS'].notnull()]
Label_train = Label_train.loc[Features_train.index]
Features_test = Features_test[Features_test['AGE_YRS'].notnull() & Features_test['NUMDAYS'].notnull()]
Label_test = Label_test.loc[Features_test.index]

# Define the bin edges for 'AGE_YRS'
bins_age = [0, 30, 60, 90, float('inf')]
labels_age = [0, 1, 2, 3]

# Create a new column 'AGE_YRS_BINNED' by cutting the 'AGE_YRS' column into bins
Features_train['AGE_YRS_BINNED'] = pd.cut(Features_train['AGE_YRS'].astype(float), bins=bins_age, labels=labels_age, include_lowest=True)
Features_test['AGE_YRS_BINNED'] = pd.cut(Features_test['AGE_YRS'].astype(float), bins=bins_age, labels=labels_age, include_lowest=True)

# Define the bin edges for 'NUMDAYS'
bins_numdays = [0, 10, 20, 30, float('inf')]
labels_numdays = [0, 1, 2, 3]

# Create a new column 'NUMDAYS_BINNED' by cutting the 'NUMDAYS' column into bins
Features_train['NUMDAYS_BINNED'] = pd.cut(Features_train['NUMDAYS'].astype(float), bins=bins_numdays, labels=labels_numdays, include_lowest=True)
Features_test['NUMDAYS_BINNED'] = pd.cut(Features_test['NUMDAYS'].astype(float), bins=bins_numdays, labels=labels_numdays, include_lowest=True)

# Transform 'VAX_MANU' performing LabelEncoder to convert categorical values of 'VAX_MANU' to integers
encoder = LabelEncoder()
Features_train['VAX_MANU'] = encoder.fit_transform(Features_train['VAX_MANU'])  # Already string, so no need to convert
Features_test['VAX_MANU'] = encoder.transform(Features_test['VAX_MANU'])  # Use transform() for test set to avoid data leakage

# Select only the binned features and the encoded 'VAX_MANU'
Features_train = Features_train[['AGE_YRS_BINNED', 'NUMDAYS_BINNED', 'VAX_MANU']]
Features_test = Features_test[['AGE_YRS_BINNED', 'NUMDAYS_BINNED', 'VAX_MANU']]

# Change data type of features, labels datasets of training, test dataset into integers
Features_train = Features_train.astype(float).astype(int)
Features_test = Features_test.astype(float).astype(int)
Label_train = Label_train.astype(int)
Label_test = Label_test.astype(int)

# Create a decision tree classifier and fit it to the training data
DecisionTree_Model = DecisionTreeClassifier(criterion='gini')
DecisionTree_Model.fit(Features_train, Label_train)

# Make predictions on the testing set
Label_pred = DecisionTree_Model.predict(Features_test)

# Calculate the accuracy and precision of the model
Accuracy = DecisionTree_Model.score(Features_test, Label_test)
Precision = precision_score(Label_test, Label_pred, average='weighted')  # Use 'weighted' for multi-class classification
F1 = f1_score(Label_test, Label_pred, average='weighted')  # Use 'weighted' for multi-class classification
Recall = recall_score(Label_test, Label_pred, average='weighted')  # Use 'weighted' for multi-class classification

# Calculate and print the confusion matrix
Confusion_Matrix = confusion_matrix(Label_test, Label_pred)

print(f"Accuracy: {Accuracy}")
print(f"Precision: {Precision}")
print(f"F1 Score: {F1}")
print(f"Recall: {Recall}")
print(f"Confusion Matrix: \n{Confusion_Matrix}")

# Convert the features and labels to values
Features_train, Label_train = Features_train.values, Label_train.values
Features_test, Label_test = Features_test.values, Label_test.values

# Print the features and label for the first 5 patients
for n in range(0,5):
    print("Patient", str(n+1), "\n  Features:", list(Features_train[n]), "\n  Label:", Label_train[n])


Number of training cases: 57381
Number of test cases: 14346
Accuracy: 0.9743567679201446
Precision: 0.967283840432478
F1 Score: 0.9688305003374905
Recall: 0.9743567679201446
Confusion Matrix: 
[[11258    55]
 [  243    65]]
Patient 1 
  Features: [0, 0, 4] 
  Label: 0
Patient 2 
  Features: [0, 0, 21] 
  Label: 0
Patient 3 
  Features: [0, 0, 10] 
  Label: 0
Patient 4 
  Features: [0, 0, 18] 
  Label: 0
Patient 5 
  Features: [0, 1, 10] 
  Label: 0


In [16]:
from sklearn.preprocessing import LabelEncoder

# Create a label encoder object
le = LabelEncoder()

# Fit and transform the 'VAX_MANU' column
DataTable['VAX_MANU'] = le.fit_transform(DataTable['VAX_MANU'])
DataTable['VAX_MANU']

# Get the list of original categories
categories = le.classes_

# Create a dictionary that maps integers to categories
int_to_category = {i: category for i, category in enumerate(categories)}

# Print the dictionary
for int_val, category in int_to_category.items():
    print(f"{int_val}: {category}")

0: BAVARIAN NORDIC
1: BERNA BIOTECH, LTD.
2: DYNAVAX TECHNOLOGIES CORPORATION
3: EMERGENT BIOSOLUTIONS
4: GLAXOSMITHKLINE BIOLOGICALS
5: INTERCELL AG
6: JANSSEN
7: MASS. PUB HLTH BIOL LAB
8: MEDIMMUNE VACCINES, INC.
9: MERCK & CO. INC.
10: MODERNA
11: MSP VACCINE COMPANY
12: NOVARTIS VACCINES AND DIAGNOSTICS
13: NOVAVAX
14: PAXVAX
15: PFIZER\BIONTECH
16: PFIZER\WYETH
17: PROTEIN SCIENCES CORPORATION
18: SANOFI PASTEUR
19: SEQIRUS, INC.
20: TEVA PHARMACEUTICALS
21: UNKNOWN MANUFACTURER
22: VBI VACCINES


In [17]:
import pandas as pd

# Assuming your features are named 'Feature1', 'Feature2', 'Feature3'
Features2 = ['AGE_YRS_BINNED','NUMDAYS_BINNED','VAX_MANU']

# Your input data
data_input2 = [3, 2, 8]

# Convert your input data into a DataFrame with feature names
data_input_df2 = pd.DataFrame([data_input2], columns=Features2)

# Now you can predict with your model
prediction2 = DecisionTree_Model.predict(data_input_df2)

print(f"Input_Class: {data_input_df2}")
print(f"Prediction_Class: {prediction2}")

Input_Class:    AGE_YRS_BINNED  NUMDAYS_BINNED  VAX_MANU
0               3               2         8
Prediction_Class: [0]


# Model 1 was better over Model 2 in predicting True Positives over false positives

# Model 3 with K-Fold logic applied to Model 1

In [10]:
ModifiedData = df[['AGE_YRS','NUMDAYS','VAX_MANU','HOSPITAL']]
ModifiedData.head(2)

AGE_YRS  NUMDAYS         VAX_MANU HOSPITAL
3      6.0      0.0  PFIZER\BIONTECH      NaN
4     38.0      0.0          MODERNA      NaN

In [11]:
from sklearn.metrics import confusion_matrix, f1_score, recall_score
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split, KFold
from sklearn.metrics import accuracy_score, precision_score
from sklearn.preprocessing import LabelEncoder
import numpy as np

# Assuming ModifiedData is your DataFrame
# Fill null values of all columns with 0
ModifiedData = ModifiedData.fillna(0)

# Ensure that all columns are of type string before performing label encoding
ModifiedData = ModifiedData.astype(str)

Features3 = ModifiedData.drop('HOSPITAL', axis=1)  # Features (all columns except 'HOSPITAL')
Label3 = ModifiedData['HOSPITAL']   # Target ('HOSPITAL' column)

# Exclude rows where 'NUMDAYS' > 31
Features3 = Features3[Features3['NUMDAYS'].astype(float) <= 31]
Label3 = Label3.loc[Features3.index]

# Transform 'HOSPITAL' rows value with "Y" to 1 and null values of 'HOSPITAL' to 0
Label3 = Label3.apply(lambda x: 1 if x == 'Y' else 0)

# Transform 'VAX_MANU' performing LabelEncoder to convert categorical values of 'VAX_MANU' to integers
encoder = LabelEncoder()
Features3['VAX_MANU'] = encoder.fit_transform(Features3['VAX_MANU'])  # Already string, so no need to convert

# Change data type of features, labels datasets into integers
Features3 = Features3.astype(float).astype(int)
Label3 = Label3.astype(int)

# Create a decision tree classifier
DecisionTree_Model = DecisionTreeClassifier(criterion='gini')

# Define the K-fold Cross Validator
kfold = KFold(n_splits=5, shuffle=True, random_state=42)

# K-fold Cross Validation model evaluation
fold_no = 1
for train, test in kfold.split(Features3, Label3):

    # Fit data to model
    DecisionTree_Model.fit(Features3.iloc[train], Label3.iloc[train])

    # Generate predictions
    Label3_pred = DecisionTree_Model.predict(Features3.iloc[test])

    # Calculate the accuracy and precision of the model
    Accuracy = DecisionTree_Model.score(Features3.iloc[test], Label3.iloc[test])
    Precision = precision_score(Label3.iloc[test], Label3_pred, average='weighted')  # Use 'weighted' for multi-class classification
    F1 = f1_score(Label3.iloc[test], Label3_pred, average='weighted')  # Use 'weighted' for multi-class classification
    Recall = recall_score(Label3.iloc[test], Label3_pred, average='weighted')  # Use 'weighted' for multi-class classification

    # Calculate and print the confusion matrix
    Confusion_Matrix = confusion_matrix(Label3.iloc[test], Label3_pred)

    print(f"Fold {fold_no} | Accuracy: {Accuracy} | Precision: {Precision} | F1 Score: {F1} | Recall: {Recall}")
    print(f"Confusion Matrix: \n{Confusion_Matrix}\n")

    fold_no = fold_no + 1


Fold 1 | Accuracy: 0.9696917661200309 | Precision: 0.9619970626614744 | F1 Score: 0.964809965956955 | Recall: 0.9696917661200309
Confusion Matrix: 
[[11223    95]
 [  258    71]]

Fold 2 | Accuracy: 0.969520048081051 | Precision: 0.9629477323638224 | F1 Score: 0.9654239471984848 | Recall: 0.969520048081051
Confusion Matrix: 
[[11206   105]
 [  250    86]]

Fold 3 | Accuracy: 0.9698608964451314 | Precision: 0.9629796692855883 | F1 Score: 0.9652875101912931 | Recall: 0.9698608964451314
Confusion Matrix: 
[[11205    93]
 [  258    90]]

Fold 4 | Accuracy: 0.9712347587154387 | Precision: 0.9665094383832781 | F1 Score: 0.9685223905868996 | Recall: 0.9712347587154387
Confusion Matrix: 
[[11227   119]
 [  216    84]]

Fold 5 | Accuracy: 0.968487034174824 | Precision: 0.9629392446261928 | F1 Score: 0.9652344566236137 | Recall: 0.968487034174824
Confusion Matrix: 
[[11186   125]
 [  242    93]]



In [12]:
import pandas as pd

# Assuming your features are named 'Feature1', 'Feature2', 'Feature3'
Features3 = ['AGE_YRS','NUMDAYS','VAX_MANU']

# Your input data
data_input3 = [30, 4, 2]

# Convert your input data into a DataFrame with feature names
data_input_df3 = pd.DataFrame([data_input3], columns=Features3)

# Now you can predict with your model
prediction3 = DecisionTree_Model.predict(data_input_df3)

print(f"Input_Class: {data_input_df3}")
print(f"Prediction_Class: {prediction3}")

Input_Class:    AGE_YRS  NUMDAYS  VAX_MANU
0       30        4         2
Prediction_Class: [0]


In [13]:
import pandas as pd

# Assuming your features are named 'Feature1', 'Feature2', 'Feature3'
Features3 = ['AGE_YRS','NUMDAYS','VAX_MANU']

# Your input data
data_input3 = [60, 30, 16]

# Convert your input data into a DataFrame with feature names
data_input_df3 = pd.DataFrame([data_input3], columns=Features3)

# Now you can predict with your model
prediction3 = DecisionTree_Model.predict(data_input_df3)

print(f"Input_Class: {data_input_df3}")
print(f"Prediction_Class: {prediction3}")

Input_Class:    AGE_YRS  NUMDAYS  VAX_MANU
0       60       30        16
Prediction_Class: [1]
